Blog_5-18-11-2014/Blog_5-18-11-2014/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Blog_5_18_11_2014.Models
{
    public class Tag
    {
        public int TagID { set; get; }
        public String content { set; get; }

        public virtual ICollection<Post> Posts { set; get; }
    }
}

Blog_5-18-11-2014/Blog_5-18-11-2014/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_5_18_11_2014.Models;

namespace Blog_5_18_11_2014.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private BlogDBContext db = new BlogDBContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProFile);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewData["idpost"] = id;
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        public ActionResult Create(Post post,string content)
        {
            if (ModelState.IsValid)
            {
                int userID = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;

                post.DateCreated = DateTime.Now;
                // Tao list cac Tag
                List<Tag> Tags = new List<Tag>();
                // Tach cac tag theo dau ,
                string[] TagContent = content.Split(',');
                // Lap cac tag vua tach
                foreach (string item in TagContent)
                {
                    //Tim xem Tag Content da co hay chua
                    Tag TagExits = null;
                    var ListTag = db.Tags.Where(y => y.content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        // neu co tag roi thi them post vao 
                        TagExits = ListTag.First();
                        TagExits.Posts.Add(post);
                    }
                    else
                    {
                        // neu chua co tag thi tao moi
                        TagExits = new Tag();
                        TagExits.content = item;
                        TagExits.Posts = new List<Post>();
                        TagExits.Posts.Add(post);
                    }
                    //add vao List cac Tag
                    Tags.Add(TagExits);
                }
                //Gan list Tag cho Post
                post.Tags = Tags;

                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_5-18-11-2014/Blog_5-18-11-2014/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_5_18_11_2014.Models;

namespace Blog_5_18_11_2014.Controllers
{
    public class TagController : Controller
    {
        private BlogDBContext db = new BlogDBContext();

        //
        // GET: /Tag/

        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        //
        // GET: /Tag/Details/5

        public ActionResult Details(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // GET: /Tag/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tag/Create

        [HttpPost]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        //
        // GET: /Tag/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Edit/5

        [HttpPost]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        //
        // GET: /Tag/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_5-18-11-2014/Blog_5-18-11-2014/Views/Tag/Create.cshtml
@model Blog_5_18_11_2014.Models.Tag

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.content)
            @Html.ValidationMessageFor(model => model.content)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_5-18-11-2014/Blog_5-18-11-2014/Views/Tag/Delete.cshtml
@model Blog_5_18_11_2014.Models.Tag

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Tag</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.content)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog_5-18-11-2014/Blog_5-18-11-2014/Views/Tag/Details.cshtml
@model Blog_5_18_11_2014.Models.Tag

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Tag</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.content)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.content)
    </div>
</fieldset>

<fieldset>
    <legend>List(Posts)</legend>
    <table>
     @foreach (var post in Model.Posts.OrderByDescending(x => x.DateCreated)) 
     {
    <tr>
        <th>
            @Html.DisplayNameFor(model => post.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => post.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => post.DateCreated)
        </th>
        <th></th>
    </tr>
     
    <tr>
        <td>
            @Html.DisplayFor(modelItem => post.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => post.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => post.DateCreated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit/"+post.ID,"Post") |
            @Html.ActionLink("Details", "Details/"+post.ID, "Post") |
            @Html.ActionLink("Delete", "Delete/"+post.ID, "Post")
        </td>
    </tr>
    }
    </table>
</fieldset>

<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.TagID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Blog_5-18-11-2014/Blog_5-18-11-2014/Views/Tag/Edit.cshtml
@model Blog_5_18_11_2014.Models.Tag

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Tag</legend>

        @Html.HiddenFor(model => model.TagID)

        <div class="editor-label">
            @Html.LabelFor(model => model.content)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.content)
            @Html.ValidationMessageFor(model => model.content)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_5-18-11-2014/Blog_5-18-11-2014/Views/Tag/Index.cshtml
@model IEnumerable<Blog_5_18_11_2014.Models.Tag>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.content)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.content)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TagID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TagID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TagID })
        </td>
    </tr>
}

</table>